### ISSUE TITLE
JustLootIt fails to load after upgrade to 1.21.3

### ISSUE THREAD

**Issue by BEMZ01** [Lauriichan/JustLootIt#29]
### Plugin version

2.1.0

### With what do you need help?

I'm not sure if im missing a dependency or if i need to reset my configuration file maybe?

### Additional Information

In the console i get this:
```
[17:15:54 ERROR]: [JustLootIt] Failed to load plugin part:
[17:15:54 ERROR]: [JustLootIt] java.lang.NullPointerException: Cannot invoke "String.substring(int)" because the return value of "me.lauriichan.spigot.justlootit.platform.IVersion.packageVersion()" is null
	at me.lauriichan.spigot.justlootit.platform.IVersion.coreVersion(IVersion.java:8)
	at me.lauriichan.spigot.justlootit.JustLootItPlugin.initVersionHandler(JustLootItPlugin.java:486)
	at me.lauriichan.spigot.justlootit.JustLootItPlugin.setupVersionHandler(JustLootItPlugin.java:144)
	at me.lauriichan.spigot.justlootit.JustLootItPlugin.onPluginLoad(JustLootItPlugin.java:133)
	at me.lauriichan.spigot.justlootit.shaded.pluginbase.BasePlugin.onLoad(BasePlugin.java:133)
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
	at java.lang.Thread.run(Thread.java:1583)
```

**Comment by Lauriichan** [comment]
What server software are you using?

**Comment by BEMZ01** [comment]
I'm upgrading from paper 1.21.1 build 128 to paper 1.21.3 build 81 (latest stable)

**Comment by Lauriichan** [comment]
https://www.spigotmc.org/resources/justlootit-unique-loot-for-everyone.116493/update?update=572558
Get the update here
